#ifndef __BPROF_IDS__H
#define __BPROF_IDS__H

enum bprof_ID {
	BPT_LOOP = 0,
 	BPT_EM_WAITING,
	BPT_EM_HEVENTS,
	BPT_EM_DISPATCH,
	BPT_EM_HEVENT,
	BPT_EM_CHKTIMEOUT,
	BPT_CONN_READABLE,
	BPT_CONN_WRITABLE,
	BPT_CONN_SENDMESSAGE,
	BPT_CONN_WRITEN,
	BPT_BUTT
};

#endif /* __BPROF_IDS__H */
